// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/grupokindynos/common/obol (interfaces: ObolService)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	obol "github.com/grupokindynos/common/obol"
	reflect "reflect"
)

// MockObolService is a mock of ObolService interface
type MockObolService struct {
	ctrl     *gomock.Controller
	recorder *MockObolServiceMockRecorder
}

// MockObolServiceMockRecorder is the mock recorder for MockObolService
type MockObolServiceMockRecorder struct {
	mock *MockObolService
}

// NewMockObolService creates a new mock instance
func NewMockObolService(ctrl *gomock.Controller) *MockObolService {
	mock := &MockObolService{ctrl: ctrl}
	mock.recorder = &MockObolServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockObolService) EXPECT() *MockObolServiceMockRecorder {
	return m.recorder
}

// GetCoin2Rates mocks base method
func (m *MockObolService) GetCoin2Rates(arg0, arg1, arg2 string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoin2Rates", arg0, arg1, arg2)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoin2Rates indicates an expected call of GetCoin2Rates
func (mr *MockObolServiceMockRecorder) GetCoin2Rates(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoin2Rates", reflect.TypeOf((*MockObolService)(nil).GetCoin2Rates), arg0, arg1, arg2)
}

// GetCoin2RatesWithAmount mocks base method
func (m *MockObolService) GetCoin2RatesWithAmount(arg0, arg1, arg2, arg3 string) (obol.CoinToCoinWithAmountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoin2RatesWithAmount", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(obol.CoinToCoinWithAmountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoin2RatesWithAmount indicates an expected call of GetCoin2RatesWithAmount
func (mr *MockObolServiceMockRecorder) GetCoin2RatesWithAmount(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoin2RatesWithAmount", reflect.TypeOf((*MockObolService)(nil).GetCoin2RatesWithAmount), arg0, arg1, arg2, arg3)
}

// GetCoinRates mocks base method
func (m *MockObolService) GetCoinRates(arg0, arg1 string) ([]obol.Rate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoinRates", arg0, arg1)
	ret0, _ := ret[0].([]obol.Rate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoinRates indicates an expected call of GetCoinRates
func (mr *MockObolServiceMockRecorder) GetCoinRates(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoinRates", reflect.TypeOf((*MockObolService)(nil).GetCoinRates), arg0, arg1)
}
